### ISSUE TITLE
Area

### ISSUE THREAD

**Issue by ashutoshcp** [deepuguptacp/c-codes#3]
1. C Program to Calculate Area and Circumference of Circle
2. C Program to Calculate Area of Scalene Triangle
3. C Program to Calculate Area of Equilateral Triangle
4. C Program to Calculate Area of Right angle Triangle
5. C Program to Calculate Area of Circle
6. C Program to Calculate Area of Rectangle
7. C Program to Calculate Area of Square
do it by tomorrow evening....

**Comment by ashutoshcp** [comment]
[scalene triangle](http://mathworld.wolfram.com/ScaleneTriangle.html)

**Comment by deepuguptacp** [comment]
i have submitted surji . plz check

**Comment by ashutoshcp** [comment]
diid you check scalene above ?
