### ISSUE TITLE
Mathematical Programs

### ISSUE THREAD

**Issue by ashutoshcp** [deepuguptacp/c-codes#4]
1 | Compute sum of the array elements using pointers 
2 | Find exponent Power Series 
3 | Read the values of x y and z and print the results expressions in one line.
4 | Reads customer number and power consumed and prints amount to be paid
5 | Find greatest in 3 numbers
6 | Calculate gross salary of a person.
7 | Reverse a given number 
8 | Calculate sum of 5 subjects and Find percentage
9 | Convert temperature from degree centigrade to Fahrenheit
10 | Find the simple interest
11 | Find area and circumference of circle
12 | Find sum of two numbers
13 | Find Factorial of Number Using Recursion
14 | Find Factorial of Number without using function
15 | Print table of n and square of n using pow()

**Comment by ashutoshcp** [comment]
14 jan

**Comment by deepuguptacp** [comment]
yes sir

**Comment by ashutoshcp** [comment]
which ones are completed?
